version: 0.2

env:
  variables:
    SENTRY_ORG: astrobin
    SENTRY_PROJECT: astrobin-ng-dev
    SENTRY_ENVIRONMENT: cypress

phases:
  install:
    runtime-versions:
      nodejs: 12

  pre_build:
    commands:
      - node --version
      - npm --version
      - npm ci
      - curl -sL https://sentry.io/get-cli/ | SENTRY_CLI_VERSION="2.6.0" bash

  build:
    commands:
      - sentry-cli releases new -p $SENTRY_PROJECT $SENTRY_RELEASE
      - sentry-cli releases set-commits $SENTRY_RELEASE --auto
      - npm run lint
      - npm run build:prod
      - npm run build:ssr:prod

  post_build:
    commands:
      - npm run test
      - npm run cy:serve-and-run
      - sentry-cli releases files $SENTRY_RELEASE upload-sourcemaps dist/frontend/browser/
      - sentry-cli releases finalize $SENTRY_RELEASE
      - sentry-cli releases deploys $SENTRY_RELEASE new -e $SENTRY_ENVIRONMENT
    finally:
      - aws configure set aws_access_key_id ${AWS_ACCESS_KEY_ID}
      - aws configure set aws_secret_access_key ${AWS_SECRET_ACCESS_KEY}
      - aws s3 cp $CODEBUILD_SRC_DIR/cypress s3://astrobin-ng-cypress-output/ --recursive

artifacts:
  files:
    - '**/*'
  base-directory: dist/frontend
