version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16

  pre_build:
    commands:
      - node --version
      - npm --version
      - npm ci --legacy-peer-deps

  build:
    commands:
      - npm run build:prod
      - bash sentry.sh
